[package]
name = "rustodo"
version = "0.1.0"
edition = "2021"
authors = ["Jamie Blättler"]

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
csv = "1.3.0"
serde = { version = "1.0.209", features = ["derive"] }
tabled = "0.16.0"